name: TODO_package_name

channels:
  - default
  - conda-forge

dependencies:
  - python>=3.11
  - ipython
  - ipykernel
  - pre-commit

  - numpy
  - pandas>=2.0
  - pytables
  - submitit

  # PyTorch:
  # - pytorch::pytorch
  # - pytorch::torchvision
  # - huggingface::transformers

  # JAX:
  # - conda-forge::jax

  - pip
  - pip:
      - -e .
